version: "3.2"
services:
  go_server:
    build: 
      context: ./go-server
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./go-server
        target: /app
    links:
      - mongo_db
  mongo_db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
volumes:
  mongo-data:
