version: "3"
services:
  go_server:
    build: 
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    links:
      - mongo_db
  mongo_db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
volumes:
  mongo-data:
